name: Build Geode Mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4

      - name: Install Geode
        uses: geode-sdk/setup-geode@v2

      - name: Build
        run: geode build

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: mod
          path: build/*.geode
